template: |
  You are a helpful assistant. Your task is to answer the user's question based ONLY on the provided article excerpts.

  ## User's Question:
  "{{.Topic}}"

  ## Provided Article Excerpts:
  {{.Articles}}

  ## Instructions:
  1. Read the user's question and the provided excerpts carefully.
  2. Synthesize an answer to the question using information found exclusively in the excerpts.
  3. If the excerpts do not contain relevant information to answer the question, you must respond with "I could not find any articles that directly discuss that topic."
