template: |
  You are an expert analyst. Analyze the article titled '{{.Title}}'.
  Extract the top 7-10 most important keywords AND named entities (people, companies, etc.).
  Return them as a single, comma-separated list.